version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/myapp:z
      - gems:/usr/local/bundle
    env_file:
      - docker/env.app
    depends_on:
      - db
  db:
    image: 'postgres:9.5'
    env_file:
      - docker/env.db
    ports:
      - 54321:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}
  gems: {}
