version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/myapp:z
      - gems:/usr/local/bundle
    env_file:
      - docker/env.app
    depends_on:
      - db
  db:
    image: 'postgres:9.5'
    env_file:
      - docker/env.db
    ports:
      - 54321:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    platform: linux/amd64
    image: 'redis:6.2.6-alpine'
    ports:
      - 6379:6379
    command: 'redis-server'
    volumes:
      - redis:/var/lib/redis/data
volumes:
  postgres_data: {}
  redis: {}
  gems: {}
